#!/usr/bin/python3

import  matplotlib.pyplot    as   plt
#   only  loading  python ori  lib 

player=["Virat","Dhoni","Rohit","Dhawan"]  #players name
runs=[120,150,78,140]  #player runs in a series


plt.xlabel("players")   # labeling on graph
plt.ylabel("runs")

plt.bar(player,runs)     # Bar plot visualization

plt.grid(color='green')  #  to form  grid  in graph 
plt.legend()  # to show labels with plot  
plt.show()    # To show ploted graph on screen
